language: java
jdk:
  - oraclejdk11
node_js:
  - 12.14.0
before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  skip_cleanup: true
  run:
after_deploy: "echo 'end'"
